baseURL: "https://wdd.js.org"
title: "The SIP Lab"
pagination:
  pagerSize: 10
# theme: ananke
theme: PaperMod
ignoreLogs:
  - 'warning-goldmark-raw-html'
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
timeZone: "Asia/Shanghai"
#googleAnalytics: G-SGW660ZWKM

minify:
  disableXML: true
  minifyOutput: true

mainSections:
  - posts

DefaultContentLanguage: zh
defaultContentLanguageInSubdir: true
languages:
  zh:
    languageName: "中文"
    weight: 1
  en:
    languageName: English
    weight: 1

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "The SIP Lab"
  description: "Deep dives into VoIP, SIP, OpenSIPS, and Kamailio."
  keywords: ["OpenSIPS", "Kamailio", "VoIP", "SIP", "FreeSWITCH", "RTC", "通信工程", "WebRTC", "电话", "PSTN", "SIP服务器", "软交换", "CTI", "CSTA"]
  author: "Eddie Wang"
  DateFormat: "2006-01-02 15:04:05"
  defaultTheme: light #auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowAllPagesInArchive: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  customcss:
    - "/font-awesome/css/font-awesome.min.css"

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"
    
    css:
      - "https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css"

  label:
    text: "The SIP Lab"
    icon: "/favicon.ico"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "Eddie Wang"
    subtitle: "前端/软交换开发"
    imageUrl: "/images/my.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: 文章
        url: posts
      - name: 标签
        url: tags

  # home-info mode
  homeInfoParams:
    enabled: false
    Title: "The SIP Lab"
    Content: "Deep dives into VoIP, SIP, OpenSIPS, and Kamailio."

  socialIcons:
    - name: github
      url: "https://github.com/wangduanduan"
    - name: discord
      url: "https://discord.gg/duayDtk6Ht"
    - name: email
      url: "mailto:eddie2072@icloud.com"
    - name: RSS
      url: "https://wdd.js.org/index.xml"

  # analytics:
  #   google:
  #     SiteVerificationTag: "G-SGW660ZWKM"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: id_opensips
      name: "OpenSIPS"
      url: /opensips/
      weight: 1
    - identifier: id_kama
      name: "Kamailio"
      url: /kamailio/
      weight: 2
    - identifier: id_fs
      name: "FreeSWITCH"
      url: /freeswitch/
      weight: 3
    - identifier: id_net
      name: "Network"
      url: /network/
      weight: 4
    - identifier: id_search
      name: "Search"
      url: /search/
      weight: 4
    - identifier: id_archives
      name: "Journal"
      url: /archives/
      weight: 5
    - identifier: id_about
      name: "Me"
      url: /about/
      weight: 6
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
  renderer:
    unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary